name: Flask Unit Testing

on:
  pull_request:
    branches:
      - '**'  # This will match all branches

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CHROMA_STORE: ./tests/chroma_data
      DATABASE_URL: postgresql://notesai_user:LS9drpA2s84V7RDtkCwuWwDKJTSl3C78@dpg-cjeh0egcfp5c73en5s40-a.ohio-postgres.render.com/notesai
      TOKENIZERS_PARALLELISM: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This will ensure the entire git history is downloaded    

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  # Adjust to the version you're using

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source env/bin/activate
        pytest

    - name: Fetch Source Branch
      run: git fetch origin ${{ github.head_ref }}

    - name: Merge to main branch
      if: success()  # This will ensure this step is only run if the previous steps were successful
      run: |
        git checkout main
        git merge --no-ff origin/${{ github.head_ref }}
        git push origin main