name: Flask Unit Testing

on:
  push:
    branches:
      - '**'  # This will match all branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12  # Adjust to the version you're using

    - name: Create virtual environment and install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source env/bin/activate
        pytest